apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: leanny
data:
  config.yaml: |
    tunnel: 24792a4f-e50e-4ff0-aa97-9d6ad9e4dc24
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: leanny.org
        service: http://leanny-site.leanny.svc.cluster.local:80
      - service: http_status:404
